---
#Select Catalyst Cennter version, this one overwrite the default version from host file
catalystcenter_version: 2.3.7.6
catalystcenter_verify: false
jinjatemplate: true
jinjatemplate_file: ../jinja_template/accesspoints_configuration_template.j2
design_sites: []
