---
- name: Configure application policy on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - vars/credentials.yml
  connection: local
  gather_facts: false
  tasks:
    - name: Create application policy
      cisco.catalystcenter.application_policy_workflow_manager:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        catalystcenter_log_level: DEBUG
        config_verify: true
        catalystcenter_api_task_timeout: 1000
        catalystcenter_task_poll_interval: 1
        state: merged
        config:
          - application_policy:
              - name: "test_policy_1"
                policy_status: "deployed"
                site_names: ["Global/Chennai/LTTS/FLOOR11"]
                device_type: "wired"
                application_queuing_profile_name: "a5"
                clause:
                  - clause_type: "BUSINESS_RELEVANCE"
                    relevance_details:
                      - relevance: "BUSINESS_RELEVANT"
                        application_set_name: ["file-sharing"]
                      - relevance: "BUSINESS_IRRELEVANT"
                        application_set_name: ["email", "backup-and-storage"]
                      - relevance: "DEFAULT"
                        application_set_name: ["collaboration-apps", "tunneling", "general-media"]
