---
- name: Play
  hosts: localhost
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create an application
      cisco.catalystcenter.applications:
        _host: "{{ _host }}"
        _username: "{{ _username }}"
        _password: "{{ _password }}"
        _verify: "{{ _verify }}"
        _debug: "{{ _debug }}"
        state: present
        payload:
          - name: itunes-video
            networkApplications:
              - id: d4658954-ef8e-4eb9-a663-d53e3f4de325
                appProtocol: tcp
                applicationSubType: NONE
                applicationType: DEFAULT
                categoryId: edc1f53c-d89d-4e8d-a23b-6148e3857504
                displayName: "12608"
                engineId: "13"
                helpString: iTunes video streaming
                longDescription: >-
                  iTunes is a media player and library app by Apple Inc. for playing, downloading, and organizing digital
                  media on OS X and Windows PCs. Users can purchase and download content through iTunes Store. iTunes-video
                  covers all video streaming from iTunes like movies and TV shows.
                name: itunes-video
                popularity: "10"
                rank: "65535"
                selectorId: "572"
                trafficClass: MULTIMEDIA_STREAMING
            networkIdentity:
              - id: 4babbfcf-c5b7-4105-8954-1ee3a6097753
                displayName: "1461196"
                lowerPort: "0"
                ports: "80"
                protocol: TCP
                upperPort: "0"
            applicationSet:
              idRef: d31b81a3-a599-4d0c-bb6d-42bbdd0e7889
      register: application_result
    - name: Get task info
      cisco.catalystcenter.task_info:
        _host: "{{ _host }}"
        _username: "{{ _username }}"
        _password: "{{ _password }}"
        _verify: "{{ _verify }}"
        taskId: "{{ application_result.catalystcenter_response.response.taskId }}"
      when:
        - application_result.catalystcenter_response is defined
        - application_result.catalystcenter_response.response is defined
        - application_result.catalystcenter_response.response.taskId is defined
      register: task_result
    - name: Show new application_set
      ansible.builtin.debug:
        msg: "{{ application_result }}"
      when:
        - application_result is defined
    - name: Show retrieved task
      ansible.builtin.debug:
        msg: "{{ task_result.catalystcenter_response.response }}"
      when:
        - task_result is defined
        - task_result.catalystcenter_response is defined
