---
# Playbook 1 Configure Network Switch Profiles on Cisco Catalyst Center
- name: Configure Network Switch Profiles on Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - vars/credentials.yml
  tasks:
    - name: Create network profile for switch
      cisco.catalystcenter.network_profile_switching_workflow_manager:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        catalystcenter_log_level: DEBUG
        config_verify: true
        catalystcenter_api_task_timeout: 1000
        catalystcenter_task_poll_interval: 1
        state: merged
        config:
          - profile_name: Campus_Access_Switch
            day_n_templates:
              - Template Provisioning To Device
            site_names:
              - Global/APO
              - Global/Abc
          - profile_name: DataCenter_Core_Switch
            day_n_templates:
              - Template Provisioning To Device
            site_names:
              - Global/Chennai
              - Global/Madurai
      register: output_list
