---
- name: Configure device credentials on Cisco CATALYST Center
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "input_swim.yml" #Contains image and device details
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.catalystcenter.swim_intent:
        host: "{{ host }}"
        api_port: "{{ api_port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        verify: "{{ verify }}"
        debug: "{{ debug }}"
        log: true
        config:
          - import_image_details:
              type: "{{ item.type }}"
              url_details:
                payload: "{{ item.url_details.payload }}"
            tagging_details:
              device_role: "{{ item.device_role }}"
              device_family_name: "{{ item.device_family_name }}"
              device_type: "{{ item.device_type }}"
              tagging: true
            image_distribution_details:
              site_name: "{{ item.site_name }}"
              device_role: "{{ item.device_role }}"
              device_family_name: "{{ item.device_family_name }}"
            image_activation_details:
              site_name: "{{ item.site_name }}"
              device_role: "{{ item.device_role }}"
              device_family_name: "{{ item.device_family_name }}"
              scehdule_validate: false
              distribute_if_needed: true
      with_items: '{{ image_details }}'
      tags:
        - swim
