---
name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  # pull_request:

env:
  NAMESPACE: cisco
  COLLECTION_NAME: dnac

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.17
          - stable-2.18
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: cisco-en-programmability/dnacenter-ansible

      - name: Create directory
        run: mkdir -p ./ansible_collections/${{env.NAMESPACE}}

      - name: Move repository
        run: mv ./cisco-en-programmability/dnacenter-ansible ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: |
          timeout 55m bash -c '
            while true; do echo "⏳ Sanity running..."; sleep 60; done &
            ansible-test sanity --docker --docker-privileged -v --color
          '
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint.yml .
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

  sanity-devel:
    name: Sanity (Ⓐdevel)
    runs-on: ubuntu-22.04
    continue-on-error: true   # No bloquea el resto del pipeline

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: cisco-en-programmability/dnacenter-ansible

      - name: Create directory
        run: mkdir -p ./ansible_collections/${{env.NAMESPACE}}

      - name: Move repository
        run: mv ./cisco-en-programmability/dnacenter-ansible ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install ansible-base (devel)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Run sanity tests (devel)
        run: |
          timeout 55m bash -c '
            while true; do echo "⏳ Devel sanity running..."; sleep 60; done &
            ansible-test sanity --docker --docker-privileged -v --color
          '
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint.yml .
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
